# Generated by Django 3.2.10 on 2021-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=80)),
                ('is_complete', models.BooleanField(blank=True, db_column='isComplete', null=True)),
            ],
            options={
                'db_table': 'todo',
                'managed': False,
            },
        ),
    ]
